name: security

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  security-events: write

jobs:
  security-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gitleaks (secrets)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-banner -v

      - name: Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1
        with:
          config: ./.semgrep.yml
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN || '' }}

      - name: Trivy FS (deps & vulns)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          ignore-unfixed: true
          format: sarif
          output: trivy-results.sarif
          severity: CRITICAL,HIGH

      - name: Checkov (Terraform)
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform
          quiet: true
          soft_fail: true
          output_format: sarif
          output_file_path: checkov-results.sarif

      - name: SBOM (SPDX)
        uses: anchore/sbom-action@v0
        with:
          path: .
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SARIF (Trivy)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Upload SARIF (Checkov)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif

